name: Private data check

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  privacy-check:
    uses: 7wells/repo-privacy-check-public/.github/workflows/privacy-check.yml@422ddf8ac8068c3606381222b7a4abd9815954c9
